CREATE TABLE mess(
    regNo STRING NOT NULL,
    name STRING,
    amount INT,
    PRIMARY KEY (regNo)
);

INSERT INTO mess
VALUES ("B220444CS", "NOUFAL RAHIM",19500);

INSERT INTO mess
VALUES ("B220395EE", "HANAN VENKITTA", 17490);